trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: environment
  displayName: Environment
  type: string
  default: dev
  values:
  - dev

variables:
  resource_counter: $[counter()]

steps:
  - checkout: self
    displayName: Checkout Infra Repo
  - task: TerraformInstaller@0
    displayName: "Install Terraform"
    inputs:
      terraformVersion: '0.12.3'
  - task: TerraformTaskV1@0
    displayName: Terraform Init
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(Build.SourcesDirectory)/Azure'
      backendServiceArm: 'Free Trial(e2919cdc-c4f0-4fc6-b544-1aa50f1054a8)'
      backendAzureRmResourceGroupName: 'am-common-resources'
      backendAzureRmStorageAccountName: 'amterraformstate'
      backendAzureRmContainerName: 'gfttechtestinfrastate'
      backendAzureRmKey: 'terraform.tfstate'
  - task: TerraformTaskV1@0
    displayName: "Terraform Apply"
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(Build.SourcesDirectory)/Azure'
      commandOptions: |
        -var "environment=${{ parameters.environment }}" -var "resource_counter=$(resource_counter)" -var "aks_serviceprincipal=$(aks_serviceprincipal)"
      environmentServiceNameAzureRM: 'Free Trial(e2919cdc-c4f0-4fc6-b544-1aa50f1054a8)'